# Write a program to input eight numbers from the user and display all the unique numbers (once).
unique_num=set()

num = input("Enter number 1:")
unique_num.add(int(num))
num = input("Enter number 2:")
unique_num.add(int(num))
num = input("Enter number 3:")
unique_num.add(int(num))
num = input("Enter number 4:")
unique_num.add(int(num))
num = input("Enter number 5:")
unique_num.add(int(num))
num = input("Enter number 6:")
unique_num.add(int(num))
num = input("Enter number 7:")
unique_num.add(int(num))
num = input("Enter number 8:")
unique_num.add(int(num))

print(unique_num)